apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: hackathon-users-service
                port:
                  number: 80
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: hackathon-users-service
                port:
                  number: 80
          - path: /video
            pathType: Prefix
            backend:
              service:
                name: hackathon-clipo-service
                port:
                  number: 80
